id: P822FEF89
initial_creation_type: ocr
source_metadata:
  volumes:
    b5bc327d08c74ff9ba88164e0eccaa97:
      base_file: v027.txt
      image_group_id: I1PD95872
      title: ལྟུང་བ་བཅོ་ལྔ་པ།
      total_pages: 1953
      volume_number: 27
